# Cơ bản về Tensor

## 1.1. Khởi tạo Tensor

In [2]:
import torch
import numpy as np
from IPython.core.history import extract_hist_ranges

In [4]:
#Khởi tạo trực tiếp từ mảng
data = [[1,2],[3,4],[5,6]]
x_data = torch.tensor(data)
print(x_data)

tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [6]:
#Tạo Tensor từ numpy array
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(x_np)

tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [7]:
# Tạo tensor từ tensor khác
x_ones = torch.ones_like(x_data)
print(f"Ones tensor: \n {x_ones} \n")
x_rand = torch.randn_like(x_data, dtype=torch.float)
print(f"Random Tensor: \n {x_rand} \n")

Ones tensor: 
 tensor([[1, 1],
        [1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[ 0.2042, -1.0943],
        [ 0.9585,  0.7055],
        [-0.5731, -0.2771]]) 



In [8]:
# Tạo các tensor từ hằng và giá trị random
shape = (2,3)
rand_tensor = torch.randn(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)
print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor} \n")

Random Tensor: 
 tensor([[-0.6347,  0.1967, -1.0508],
        [ 0.1778,  0.4728, -0.2700]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 



## 1.2. Các thuộc tính của Tensor

In [14]:
my_tensor = torch.randn(shape)
print(f"Shape of Tensor: {my_tensor.shape} \n.")
print(f"Data type of Tensor: {my_tensor.dtype} \n.")
print(f"Device of Tensor: {my_tensor.device} \n.")

Shape of Tensor: torch.Size([2, 3]) 
.
Data type of Tensor: torch.float32 
.
Device of Tensor: cpu 
.


In [15]:
# We move our tensor to the current accelerator if available
if torch.accelerator.is_available():
    tensor = my_tensor.to(torch.accelerator.current_accelerator())
print(f"Device of Tensor: {my_tensor.device} \n.")


Device of Tensor: cpu 
.


## 1.3. Các toán tử trên Tensor

In [22]:
# Truy cập chỉ mục và lát cắt như numpy
tensor = torch.rand(4,4)
print(f"Orginal Tensor: \n {tensor} \n.")
print(f"First row: {tensor[0]} \n.")
print(f"First column: {tensor[:,0]} \n.")
print(f"Last row: {tensor[:,-1]} \n.")
tensor[:,1]=0
print(tensor)

Orginal Tensor: 
 tensor([[0.3414, 0.7072, 0.4088, 0.8657],
        [0.4767, 0.0519, 0.2285, 0.6970],
        [0.6728, 0.5976, 0.0743, 0.8761],
        [0.0640, 0.3985, 0.9906, 0.3761]]) 
.
First row: tensor([0.3414, 0.7072, 0.4088, 0.8657]) 
.
First column: tensor([0.3414, 0.4767, 0.6728, 0.0640]) 
.
Last row: tensor([0.8657, 0.6970, 0.8761, 0.3761]) 
.
tensor([[0.3414, 0.0000, 0.4088, 0.8657],
        [0.4767, 0.0000, 0.2285, 0.6970],
        [0.6728, 0.0000, 0.0743, 0.8761],
        [0.0640, 0.0000, 0.9906, 0.3761]])


In [27]:
# Nối các Tensor bằng cat
t1 = torch.cat((tensor,tensor,tensor),dim=0) #dim = 0 nối theo hàng, dim = 1: nối theo cột
print(t1.shape)
print(t1)

torch.Size([12, 4])
tensor([[0.3414, 0.0000, 0.4088, 0.8657],
        [0.4767, 0.0000, 0.2285, 0.6970],
        [0.6728, 0.0000, 0.0743, 0.8761],
        [0.0640, 0.0000, 0.9906, 0.3761],
        [0.3414, 0.0000, 0.4088, 0.8657],
        [0.4767, 0.0000, 0.2285, 0.6970],
        [0.6728, 0.0000, 0.0743, 0.8761],
        [0.0640, 0.0000, 0.9906, 0.3761],
        [0.3414, 0.0000, 0.4088, 0.8657],
        [0.4767, 0.0000, 0.2285, 0.6970],
        [0.6728, 0.0000, 0.0743, 0.8761],
        [0.0640, 0.0000, 0.9906, 0.3761]])


In [30]:
# Các phép toán trên Tensor
tensor = torch.ones(4,4)
tensor[:,1]=0
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)
print(f"tensor @ tensor.T :\n {y1} \n")
print(f"tensor matmul tensor.T :\n {y2} \n")
y3 = torch.rand_like(y1)
torch.matmul(tensor,tensor.T, out=y3)

z1 = tensor * tensor
print(f"tensor * tensor \n {z1} \n")
z2 = tensor.mul(tensor)
z3 = torch.rand_like(tensor)
torch.mul(tensor,tensor,out=z3)

tensor @ tensor.T :
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) 

tensor matmul tensor.T :
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) 

tensor * tensor 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 



tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [32]:
# Tính tổng các phần tử trên Tensor
agg = tensor.sum()
print(f"tensor sum tensor \n {agg} \n")
agg_item = agg.item()
print(f"tensor sum tensor \n {agg_item} ,\t {type(agg_item)}\n")

tensor sum tensor 
 12.0 

tensor sum tensor 
 12.0 ,	 <class 'float'>



In [33]:
#Các biểu thức gán kết hợp bằng hậu tố _ đằng sau toán tử. VD: x.copy_(y); x.add_(y) ~ x+=y
print(f"tensor:{tensor}")
tensor.add_(5)

tensor:tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])

## 1.4 Chuyển đổi với

In [34]:
#Tensor to numpy array
t = torch.ones(5)
print(f"Tensor t: \n {t} \n")
n = t.numpy()
print(f"Numpy n: \n {n} \n")

Tensor t: 
 tensor([1., 1., 1., 1., 1.]) 

Numpy n: 
 [1. 1. 1. 1. 1.] 



In [35]:
# Khi convert thực chất là tham chiếu nên phép biến đổi tensor sẽ làm thay đổi numpy
t.add_(1)
print(f"Tensor t: \n {t} \n")
print(f"Numpy n: \n {n} \n")

Tensor t: 
 tensor([2., 2., 2., 2., 2.]) 

Numpy n: 
 [2. 2. 2. 2. 2.] 



In [36]:
# Numpy to tensor
n = np.ones(5)
t = torch.from_numpy(n)

In [37]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
